PROGRAM DEW
! Mon, 24 Apr 2023 14:41:12 +0900
! /work03/am/00.TOOLS/ANALYSIS/12.12.ATM/12.12.THERMO/12.12.MOIST.ADIABAT/12.12.DEWPOINT

!IMPLICIT NONE
!

REAL::TC,RH
REAL::TD

NAMELIST /PARA/TC,RH
READ(*,NML=PARA)


PRINT '(A,f7.3,A,f7.3)','TC=',TC,' RH=',RH 

TD=DWPT(TC,RH)

PRINT '(A,f7.3)','TD=',TD

END PROGRAM DEW



FUNCTION DWPT(T,RH)
! INPUT
! T: TEMPERATURE(CELSIUS) 
! RH: RELATIVE HUMIDITY (%).
!
! OUTPUT
! DEW POINT (CELSIUS)

        X = 1.-0.01*RH
! COMPUTE DEW POINT DEPRESSION.
DPD =(14.55+0.114*T)*X+((2.5+0.007*T)*X)**3+(15.9+0.117*T)*X**14

DWPT = T-DPD

! THE FORMULA IS USED IN THE
! PROCESSING OF U.S. RAWINSONDE DATA AND IS REFERENCED IN PARRY, H.
! DEAN, 1969: "THE SEMIAUTOMATIC COMPUTATION OF RAWINSONDES,"
! TECHNICAL MEMORANDUM WBTM EDL 10, U.S. DEPARTMENT OF COMMERCE,
! ENVIRONMENTAL SCIENCE SERVICES ADMINISTRATION, WEATHER BUREAU,
! OFFICE OF SYSTEMS DEVELOPMENT, EQUIPMENT DEVELOPMENT LABORATORY,
! SILVER SPRING, MD (OCTOBER), PAGE 9 AND PAGE II-4, LINE 460.
RETURN
END

