PROGRAM IMERG_TEST

CHARACTER INDIR*500,INFLE*500,IN*1000,ODIR*500,OFLE*500,&
OUT*1000

namelist /para/INDIR,INFLE,ODIR,OFLE

read(5,nml=para)

IN=TRIM(INDIR)//TRIM(INFLE)
OUT=TRIM(ODIR)//TRIM(OFLE)

PRINT '(A)',"MMMMM INPUT : "
PRINT '(A)',TRIM(IN)
PRINT '(A)',"MMMMM OUTPUT: "
PRINT '(A)',TRIM(OUT)

END PROGRAM IMERG_TEST
