PROGRAM TEST_READ_NC

INTEGER Y
CHARACTER RUN*5,YYYY*4
CHARACTER INROOT*300,INDIR*800,INFLE*500,IN*1300
CHARACTER ODIR*500,OFLE*500,OUT*1000

INTEGER,ALLOCATABLE,DIMENSION(:)::timeI
!REAL
REAL(8),ALLOCATABLE,DIMENSION(:)::lon,lat
!REAL,ALLOCATABLE,DIMENSION(:)::

!REAL,PARAMETER::UNDEF=

NAMELIST /PARA/NM,Y
READ(*,NML=PARA)

ALLOCATE(timeI(NM))

RUN="CLM"
WRITE(YYYY,'(I4.4)')Y
INROOT="/work01/DATA/J-OFURO3/V1.2_PRE/22.12.DECOMP_GLOBE/0.OUT_COR3.0_DECOMP_GLOBE_JOF3/LHF/"
INDIR=TRIM(INROOT)//TRIM(RUN)//"_RUN"
INFLE="J-OFURO3_COR3_LHF_"//TRIM(RUN)//"_RUN_DAILY_"//YYYY//'.nc'
IN=TRIM(INDIR)//'/'//TRIM(INFLE)

CALL READ_NC1FLT("time", IN, NM, timeI)

print '(A,A)','INPUT: ',trim(IN)

END PROGRAM
