PROGRAM TEST_READ_NC

INTEGER Y
CHARACTER RUN*5,YYYY*4
CHARACTER INROOT*300,INDIR*800,INFLE*500,IN*1300
CHARACTER ODIR*500,OFLE*500,OUT*1000

INTEGER,ALLOCATABLE,DIMENSION(:)::timeI
!REAL
REAL(8),ALLOCATABLE,DIMENSION(:)::lonI,latI
REAL,ALLOCATABLE,DIMENSION(:,:,:)::CLM
CHARACTER(100)::VNAME
!REAL,PARAMETER::UNDEF=

NAMELIST /PARA/NM,Y,IM,JM,VNAME
READ(*,NML=PARA)

ALLOCATE(timeI(NM))
ALLOCATE(lonI(IM),latI(JM))
ALLOCATE(CLM(IM,JM,NM))

RUN="CLM"
WRITE(YYYY,'(I4.4)')Y
INROOT="/work01/DATA/J-OFURO3/V1.2_PRE/22.12.DECOMP_GLOBE/0.OUT_COR3.0_DECOMP_GLOBE_JOF3/LHF/"
INDIR=TRIM(INROOT)//TRIM(RUN)//"_RUN"
INFLE="J-OFURO3_COR3_LHF_"//TRIM(RUN)//"_RUN_DAILY_"//YYYY//'.nc'
IN=TRIM(INDIR)//'/'//TRIM(INFLE)

CALL READ_NC1FLT("time", IN, NM, timeI)
CALL READ_NC1DBL("lon", IN, IM, lonI)
CALL READ_NC1DBL("lat", IN, JM, latI)

print '(A,i5,A,i5,A,i3)','NM=',NM,' IM=',IM,' JM=',JM

CALL READ_NC2("LHF", IN, IM,JM,NM, CLM)

END PROGRAM
