PROGRAM TEST_READ_NC

INTEGER Y
CHARACTER RUN*5,YYYY*4
CHARACTER INROOT*300,INDIR*800,INFLE*500,IN*1300
CHARACTER PREFIX*100,ODIR*500,OFLE*500,OUT*1000

INTEGER,ALLOCATABLE,DIMENSION(:)::timeI
!REAL
REAL(8),ALLOCATABLE,DIMENSION(:)::lonI,latI
REAL,ALLOCATABLE,DIMENSION(:,:,:)::&
FLX_CLM, FLX_QA, FLX_RAW, FLX_SST, FLX_WND

INTEGER,PARAMETER::NVAR=5
REAL,ALLOCATABLE,DIMENSION(:,:,:,:)::FLX_OUT

CHARACTER(100)::VNAME
CHARACTER(100),ALLOCATABLE::FLX_NAME(:)

!REAL,PARAMETER::UNDEF=

NAMELIST /PARA/NM,Y,IM,JM,VNAME
READ(*,NML=PARA)

ALLOCATE(timeI(NM))
ALLOCATE(lonI(IM),latI(JM))
ALLOCATE(FLX_CLM(IM,JM,NM), FLX_QA(IM,JM,NM), FLX_RAW(IM,JM,NM),&
FLX_SST(IM,JM,NM), FLX_WND(IM,JM,NM))
ALLOCATE(FLX_OUT(NVAR,IM,JM,NM),FLX_NAME(NVAR))

RUN="CLM"
WRITE(YYYY,'(I4.4)')Y
INROOT="/work01/DATA/J-OFURO3/V1.2_PRE/22.12.DECOMP_GLOBE/0.OUT_COR3.0_DECOMP_GLOBE_JOF3/LHF/"
INDIR=TRIM(INROOT)//TRIM(RUN)//"_RUN"
INFLE="J-OFURO3_COR3_LHF_"//TRIM(RUN)//"_RUN_DAILY_"//YYYY//'.nc'
IN=TRIM(INDIR)//'/'//TRIM(INFLE)

CALL READ_NC1FLT("time", IN, NM, timeI)
CALL READ_NC1DBL("lon", IN, IM, lonI)
CALL READ_NC1DBL("lat", IN, JM, latI)

print '(A,i5,A,i5,A,i3)','NM=',NM,' IM=',IM,' JM=',JM

print '(A)','MMMMM READ INPUT DATA'
RUN="CLM"
INDIR=TRIM(INROOT)//TRIM(RUN)//"_RUN"
INFLE="J-OFURO3_COR3_LHF_"//TRIM(RUN)//"_RUN_DAILY_"//YYYY//'.nc'
IN=TRIM(INDIR)//'/'//TRIM(INFLE)
CALL READ_NC2(TRIM(VNAME), IN, IM,JM,NM, FLX_CLM)

RUN="QA"
INDIR=TRIM(INROOT)//TRIM(RUN)//"_RUN"
INFLE="J-OFURO3_COR3_LHF_"//TRIM(RUN)//"_RUN_DAILY_"//YYYY//'.nc'
IN=TRIM(INDIR)//'/'//TRIM(INFLE)
CALL READ_NC2(TRIM(VNAME), IN, IM,JM,NM, FLX_QA)

RUN="RAW"
INDIR=TRIM(INROOT)//TRIM(RUN)//"_RUN"
INFLE="J-OFURO3_COR3_LHF_"//TRIM(RUN)//"_RUN_DAILY_"//YYYY//'.nc'
IN=TRIM(INDIR)//'/'//TRIM(INFLE)
CALL READ_NC2(TRIM(VNAME), IN, IM,JM,NM, FLX_RAW)

RUN="SST"
INDIR=TRIM(INROOT)//TRIM(RUN)//"_RUN"
INFLE="J-OFURO3_COR3_LHF_"//TRIM(RUN)//"_RUN_DAILY_"//YYYY//'.nc'
IN=TRIM(INDIR)//'/'//TRIM(INFLE)
CALL READ_NC2(TRIM(VNAME), IN, IM,JM,NM, FLX_SST)

RUN="WND"
INDIR=TRIM(INROOT)//TRIM(RUN)//"_RUN"
INFLE="J-OFURO3_COR3_LHF_"//TRIM(RUN)//"_RUN_DAILY_"//YYYY//'.nc'
IN=TRIM(INDIR)//'/'//TRIM(INFLE)
CALL READ_NC2(TRIM(VNAME), IN, IM,JM,NM, FLX_WND)



print '(A)','MMMMM COPY INPUT DATA TO ARRAY FOR OUTPUT'
FLX_NAME(1)="LHFRAW";FLX_NAME(2)="LHFCLM";FLX_NAME(3)="LHFSST"; 
FLX_NAME(4)="LHFWND";FLX_NAME(5)="LHFQA" 

DO I=1,5
IF(I==1)FLX_OUT(I,:,:,:)=FLX_RAW(:,:,:)
IF(I==2)FLX_OUT(I,:,:,:)=FLX_CLM(:,:,:)
IF(I==3)FLX_OUT(I,:,:,:)=FLX_SST(:,:,:)
IF(I==4)FLX_OUT(I,:,:,:)=FLX_WND(:,:,:)
IF(I==5)FLX_OUT(I,:,:,:)=FLX_QA(:,:,:)
END DO !I

print *

print '(A)','MMMMM WRITE DATA FOR CHECKING'
PREFIX="7TEST_READ_NC_"//TRIM(VNAME)
ODIR="."

OUT=TRIM(PREFIX)//"_"//YYYY//'.nc'

CALL WRITE_NC_ALL(NVAR, FLX_NAME, OUT, IM, JM, NM, FLX_OUT, &
timeI, latI, lonI, INDIR, INFLE, ODIR, OFLE)
print '(A,A)','OUTPUT: ',TRIM(OUT)

END PROGRAM
