PROGRAM SAMPLE_SD_DATA
! Mon, 04 Sep 2023 14:16:13 +0900
! localhost.localdomain
! /work09/am/00.WORK/2022.RW3A/16.00.EAV.TRAJ.RW3A

!IMPLICIT NONE
!
CHARACTER OUT*1000

INTEGER,PARAMETER::NT=5

!INTEGER,ALLOCATABLE,DIMENSION(:)::
!REAL
REAL,ALLOCATABLE,DIMENSION(:)::AV,SD1,SD2

!REAL,PARAMETER::UNDEF=

!NAMELIST /PARA/
!READ(*,NML=PARA)

ALLOCATE(AV(NT),SD1(NT),SD2(NT))

DO I=1,NT
AV(I)=FLOAT(I)
SD1(I)=AV(I)-0.5
SD2(I)=AV(I)+0.5
END DO !I

OUT="SAMPLE_SD_DATA.BIN"
OPEN(21,FILE=OUT,FORM='UNFORMATTED',ACCESS='DIRECT',&
RECL=4*1)
IREC=0

DO I=1,NT
IREC=IREC+1
WRITE(21,REC=IREC)AV(I)
PRINT *,AV(I),SD1(I),SD2(I)
IREC=IREC+1
WRITE(21,REC=IREC)SD1(I)
IREC=IREC+1
WRITE(21,REC=IREC)SD2(I)
END DO

CLOSE(21)

PRINT '(A,A)','OUTPUT: ',TRIM(OUT)

END PROGRAM
